package JDBCCoffeeExampleWithPool;

import JDBCCoffeeExample.model.Coffee;
import JDBCCoffeeExample.utils.SQLQueries;
import jakarta.inject.Inject;

import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CoffeeDAO {


   private final DBConnectionPool pool;

    @Inject
    public CoffeeDAO(DBConnectionPool pool) {
        this.pool = pool;
    }

    /**
     * Lists all coffees using Statement Class
     */
    public List<Coffee> getAll() {
        List<Coffee> coffees=new ArrayList<>();
        try (Connection con = pool.getConnection();
             Statement statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                     ResultSet.CONCUR_READ_ONLY)) {

            ResultSet rs = statement.executeQuery(SQLQueries.SELECT_coffees_QUERY);
            //rs.absolute(2);
            //rs.previous();
            coffees=mapCoffee(rs);

        } catch (SQLException ex) {
            Logger.getLogger(CoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        return coffees;
    }

    /**
	 * Insert, delete, update methods with using the ResultSet
	 */
	
	public void crudWithRS(Coffee coffee)  {

            try (Connection con = pool.getConnection();
                 Statement statement = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                         ResultSet.CONCUR_UPDATABLE);){

                // Select the data you need to operate, no need to read the whole table
                ResultSet rs = statement.executeQuery(SQLQueries.SELECT_coffees_QUERY);

               /*
                 * For inserting a row within the ResultSet, the cursor has to be positioned
                 * on a special row named "insert row", where values can be assigned
                 */
                rs.moveToInsertRow();

                rs.updateInt(1,coffee.getId());  //No autogenerated id
                rs.updateString("COF_NAME", coffee.getName());
                rs.updateInt("SUPP_ID", coffee.getIdSupplier());
                rs.updateFloat("PRICE", coffee.getPrice());
                rs.updateInt("SALES", coffee.getSales());
                rs.updateFloat("TOTAL", coffee.getTotal());

                // Inserts ResultSet row. Changes are saved in DB 		
                rs.insertRow();

                // Scrolls through the updated ResultSet
                rs.beforeFirst();
                System.out.println("\nAfter inserting new row:\n" + mapCoffee(rs));

                rs.beforeFirst();
                //Update price incrementing 10%
                while (rs.next()) {
                    float f = rs.getFloat("PRICE");
                    // Updates ResultSet price column
                    rs.updateFloat("PRICE", f * 1.10f);
                    // Updates ResultSet row. Changes are saved in DB
                    rs.updateRow();
                }

                rs.beforeFirst();
                System.out.println("\nAfter updating the price:\n" + mapCoffee(rs));
                // Sets the cursor before first row

                //Delete last row
                rs.last();
                rs.deleteRow();

                rs.beforeFirst();
                System.out.println("\nAfter deleting last row:\n" +  mapCoffee(rs));

                } catch (SQLException sqle) {
                Logger.getLogger(CoffeeDAO.class.getName()).log(Level.SEVERE, null, sqle);
            }
	}
        
        /**
	 * UpdateSales method: Updates coffee sales and total using a transaction
	 */
        public void updateSales(HashMap<String, Integer> sales)
	{
            try (Connection con = pool.getConnection();) {

                try (PreparedStatement pstmt = con.prepareStatement(SQLQueries.UPDATE_SALES_coffees);
                     PreparedStatement pstmt2 = con.prepareStatement(SQLQueries.UPDATE_TOTAL_COFFEE);) {

                    // Disables autocommit
                    con.setAutoCommit(false);

                    for (Map.Entry<String, Integer> e : sales.entrySet()) {
                        pstmt.setInt(1, e.getValue());
                        pstmt.setString(2, e.getKey());
                        pstmt.executeUpdate();
                        pstmt2.setFloat(1, e.getValue());
                        pstmt2.setString(2, e.getKey());
                        pstmt2.executeUpdate();

                        // Commit when all movements have been done
                        con.commit();
                    }
                } catch (SQLException sqle) {
                    Logger.getLogger(CoffeeDAO.class.getName()).log(Level.SEVERE, null, sqle);
                    try {
                        con.rollback();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    // Private methods
    private List<Coffee> mapCoffee(ResultSet rs) {
        List<Coffee> coffees = new ArrayList<>();
        try {
            while (rs.next()) {
                Coffee coffee=new Coffee();
                coffee.setId(rs.getInt("id_prod")); // also with indexes: rs.getInt(1)
                coffee.setName(rs.getString("COF_NAME")); //also with indexes: rs.getString(2)
                coffee.setIdSupplier(rs.getInt("SUPP_ID"));
                coffee.setPrice(rs.getFloat("PRICE"));
                coffee.setSales(rs.getInt("SALES"));
                coffee.setTotal(rs.getFloat("TOTAL"));
                coffees.add(coffee);
            }

        } catch (SQLException ex) {
            Logger.getLogger(CoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        return coffees;
    }

}
