package JDBCCoffeeExample;

import JDBCCoffeeExample.model.Coffee;
import JDBCCoffeeExample.utils.SQLQueries;
import jakarta.inject.Inject;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class BasicCoffeeDAO {

    private final DBConnection db;

    @Inject
    public BasicCoffeeDAO(DBConnection db) {
        this.db = db;
    }

    /**
     * Lists all coffees using Statement Class
     */
    public List<Coffee> getAll() {
        List<Coffee> coffees= new ArrayList<>();
        try (Connection con = db.getConnection();
             Statement statement = con.createStatement()) {

            ResultSet rs = statement.executeQuery(SQLQueries.SELECT_coffees_QUERY);
            coffees=mapCoffee(rs);

        } catch (SQLException ex) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
            //Throw exception?
        }
        return coffees;
    }

    /**
     * Get coffee by id
     */
    public Coffee get(int id) {
        Coffee coffee = new Coffee();
        try (Connection con = db.getConnection();
             PreparedStatement preparedStatement = con.prepareStatement(SQLQueries.SELECT_coffeeById_QUERY)){
            preparedStatement.setInt(1, id);

            // Executing the statement. The result will be stored in the ResultSet object
            ResultSet rs = preparedStatement.executeQuery();
            coffee=mapCoffee(rs).get(0);

        } catch (SQLException ex) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
            //Or throw exception
        }
        return coffee;
    }
    /**
     * Lists coffees of a given name
     */
    public List<Coffee> getAllByName(String c) {
        List<Coffee> coffees= new ArrayList<>();
        try (Connection con = db.getConnection();
        PreparedStatement preparedStatement = con.prepareStatement(SQLQueries.SELECT_coffeeByName_QUERY)) {        preparedStatement.setString(1, c);

            // Executing the statement. The result will be stored in the ResultSet object
            ResultSet rs = preparedStatement.executeQuery();
            coffees= mapCoffee(rs);

        } catch (SQLException ex) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
             //Or throw exception
        }
        return coffees;
    }


    /**
     * Method for updating coffee sales using executeUpdate method
     */
    public void update(Coffee coffee) {

        try (Connection con = db.getConnection();
             PreparedStatement preparedStatement = con.prepareStatement(SQLQueries.UPDATE_SALES_coffees)) {
            preparedStatement.setFloat(1, coffee.getSales());
            preparedStatement.setInt(2, coffee.getId());

            // executeUpdate method for INSERT, UPDATE and DELETE
            preparedStatement.executeUpdate();

        } catch (SQLException sqle) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }
    /**
     * Method for saving coffee with autogenerated key
     */
    public int save (Coffee coffee){
        int auto_id=0;
        try (Connection con = db.getConnection();
             PreparedStatement preparedStatement = con.prepareStatement(SQLQueries.INSERT_COFFEE_WITH_AUTOINCREMENTAL_ID,
                                                                Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setString(1, coffee.getName());
            preparedStatement.setInt(2, coffee.getIdSupplier());
            preparedStatement.setFloat(3, coffee.getPrice());
            preparedStatement.setInt(4, coffee.getSales());
            preparedStatement.setFloat(5, coffee.getTotal());

            int rowsAffected= preparedStatement.executeUpdate();
            ResultSet rs = preparedStatement.getGeneratedKeys();
            if(rs.next()) {
                auto_id = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        return auto_id;
    }

    /**
     * Method for deleting coffee by id
     */
    public void delete(int id) {
        try (Connection con = db.getConnection();
        PreparedStatement preparedStatement = con.prepareStatement(SQLQueries.DELETE_COFFEE)) {
            preparedStatement.setInt(1, id);
            // executeUpdate method for INSERT, UPDATE and DELETE
            //rowsAffected= preparedStatement.executeUpdate();
            preparedStatement.executeUpdate();

        } catch (SQLException sqle) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }

    // Private methods
    private List<Coffee> mapCoffee(ResultSet rs) {
        List<Coffee> coffees = new ArrayList<>();
        try {
            while (rs.next()) {
                Coffee coffee=new Coffee();
                coffee.setId(rs.getInt("id_prod")); // also with indexes: rs.getInt(1)
                coffee.setName(rs.getString("COF_NAME")); //also with indexes: rs.getString(2)
                coffee.setIdSupplier(rs.getInt("SUPP_ID"));
                coffee.setPrice(rs.getFloat("PRICE"));
                coffee.setSales(rs.getInt("SALES"));
                coffees.add(coffee);
          }

        } catch (SQLException ex) {
            Logger.getLogger(BasicCoffeeDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        return coffees;
    }

}
